
spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      springframework:
        security: TRACE
        jpa: DEBUG
app:
  constants:
    user-defaults:
      max-photos:
        single: 20
        collection: 20
    security:
      jwt-secret-key: 56bb52a9882a6z7bfd065c980908a4e656fd52a9882a6b7bfa065c982907a4e6