
spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      springframework:
        jpa: DEBUG